version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: kosync-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: KosyncDb
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - kosync-network

  mongoku:
    image: huggingface/mongoku:latest
    container_name: kosync-mongoku
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://admin:adminpassword@mongodb:27017"
    depends_on:
      - mongodb
    networks:
      - kosync-network

  kosync-app:
    build: .
    image: kosync:latest
    container_name: kosync-application
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      MongoDB__ConnectionString: "mongodb://admin:adminpassword@mongodb:27017/KosyncDb?authSource=admin"
      MongoDB__DatabaseName: "KosyncDb"
      MongoDB__AdminPassword: "adminpassword"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - mongodb
    networks:
      - kosync-network

networks:
  kosync-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local