version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: kosync-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: KosyncDb
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  
  
  mongoku:
    image: huggingface/mongoku:latest
    container_name: kosync-mongoku
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      MONGOKU_DEFAULT_HOST: "mongodb://admin:adminpassword@host.docker.internal:27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local